apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: aws-account-vending
  title: AWS Account Vending Request
  description: Request a new AWS account via AFT
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters: 
  - title: AWS Account Name
    description: Enter the name for the new AWS Account
    required: true
    type: string
    name: accountName
  - title: Environment
    description: Select the env for this account
    required: true
    name: environment
    enum:
      - dev
      - test
      - prod
  - title: Owner Email
    description: Enter the email address of the account owner
    required: true
    type: string
    name: ownerEmail
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: submit-request
      name: Submit
      action: humanitec.submitAccountRequest
      input:
        accountName: ${{ parameters.accountName }}
        environment: ${{ parameters.environment }}
        ownerEmail: ${{ parameters.ownerEmail }}
